[package]
name = "cranelift-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["cargo"] }
cranelift = "0.128.3"
cranelift-module = "0.128.3"
cranelift-object = "0.128.3"
